//header automatically generated by autoHead
#pragma once
#include "string_debug.h"
#include <assert.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>
int testIndex();
int replaceTest();
int removeTest();
